CREATE TABLE IF NOT EXISTS `billdb`.`Monitors` (
  `SKEY` INT(11) NOT NULL AUTO_INCREMENT,
  `GUID` VARCHAR(32) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`SKEY`),
  UNIQUE INDEX `GUID_UNIQUE` (`GUID` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1