CREATE TABLE IF NOT EXISTS `billdb`.`Monitors` (
  `SKEY` INT(11) NOT NULL AUTO_INCREMENT,
  `GUID` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`SKEY`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1