CREATE TABLE IF NOT EXISTS `billdb`.`Schedule` (
  `SKEY` INT(11) NOT NULL AUTO_INCREMENT,
  `GUID` VARCHAR(32) NULL DEFAULT NULL,
  `body` MEDIUMTEXT NULL DEFAULT NULL,
  `date` DATE NOT NULL,
  `Monitors_SKEY` INT(11) NOT NULL,
  PRIMARY KEY (`SKEY`, `Monitors_SKEY`),
  INDEX `fk_Schedule_Monitors1_idx` (`Monitors_SKEY` ASC) VISIBLE,
  CONSTRAINT `fk_Schedule_Monitors1`
    FOREIGN KEY (`Monitors_SKEY`)
    REFERENCES `billdb`.`Monitors` (`SKEY`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1