CREATE TABLE IF NOT EXISTS `billdb`.`Videos` (
  `SKEY` INT NOT NULL AUTO_INCREMENT,
  `GUID` VARCHAR(32) NOT NULL,
  `link` VARCHAR(256) NOT NULL,
  `name` VARCHAR(256) NULL,
  `users_SKEY` INT NOT NULL,
  PRIMARY KEY (`SKEY`, `users_SKEY`),
  UNIQUE INDEX `SKEY_UNIQUE` (`SKEY` ASC) VISIBLE,
  UNIQUE INDEX `GUID_UNIQUE` (`GUID` ASC) VISIBLE,
  INDEX `fk_Videos_users_idx` (`users_SKEY` ASC) VISIBLE,
  CONSTRAINT `fk_Videos_users`
    FOREIGN KEY (`users_SKEY`)
    REFERENCES `andrew_test`.`users` (`SKEY`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB